export async function GET() {
    const xsl = `<?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet version="1.0"
      xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  
      <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  
      <xsl:template match="/">
        <html>
          <head>
            <title>Sitemap</title>
            <style>
              body { font-family: sans-serif; padding: 2rem; background: #f9f9f9; max-width: 900px; margin: auto; }
              h1 { color: #000000; }
              p.count { margin-top: ; color: #555; font-size: 14px; }
              p.expl { color: #555; font-size: 14px; }
              a { color: #38aaeb; text-decoration: none; font-weight: bold; }
              table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
              th, td { font-size: 11px; padding: 4px; border: 1px solid #ddd; text-align: left; }
              th { background-color: #38aaeb; color: white; } 
              tr:nth-child(even) { background-color: #f2f2f2; }
              tr:hover { background-color: #c7e0ef; }
              td a { font-size: 11px; font-weight: normal; color: #000000; text-decoration: none; }
              td a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>SED XML Sitemap</h1>
            
            <p class="expl">
              Generated by <a href="https://www.sysgenix.com">Sysgenix Technologies</a>, this is an XML Sitemap, meant for consumption by search engines.<br/> <br/>
              You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.
            </p>
            <p class="count">This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
            <table>
              <thead>
                <tr><th>URL</th><th>Last Modified</th></tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </body>
        </html>
      </xsl:template>
    </xsl:stylesheet>`
  
    return new Response(xsl, {
      headers: {
        'Content-Type': 'text/xsl',
      },
    });
  }
  